### ISSUE TITLE
Panic on exec block: runtime error: index out of range

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#1139]
**Describe the bug**

Don't know if this is reproducible, but incase anyone experiences this Tendermint issue please comment here

```
panic: runtime error: index out of range [2821] with length 2821

goroutine 5865 [running]:
github.com/tendermint/tendermint/state.execBlockOnProxyApp.func1(0xc007a285a0, 0xc007a285d0)
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/state/execution.go:288 +0x204
github.com/tendermint/tendermint/abci/client.(*localClient).callback(0xc0013ba2a0, 0xc007a285a0, 0xc007a285d0, 0x592)
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/abci/client/local_client.go:246 +0x3e
github.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc0013ba2a0, 0xc002878600, 0x592, 0x592, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/abci/client/local_client.go:89 +0x2c8
github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc000a5b390, 0xc002878600, 0x592, 0x592, 0x0, 0x0, 0x0, 0x0, 0xc0013c9350)
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/proxy/app_conn.go:73 +0x5e
github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x4fdb5e0, 0xc003cabc20, 0x4fe4ee0, 0xc000a5b390, 0xc009eded20, 0x4fedbe0, 0xc000f19b80, 0x7, 0xc00e5f1410, 0x7)
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/state/execution.go:311 +0x613
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00e49c680, 0xa, 0x0, 0xc00e5f1400, 0x7, 0xc00e5f1410, 0x7, 0x1ba9, 0x43e11, 0xc00a199000, ...)
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/state/execution.go:135 +0x17a
github.com/tendermint/tendermint/blockchain/v1.(*BlockchainReactor).processBlock(0xc001c72600, 0xc002004480, 0x0)
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/blockchain/v1/reactor.go:432 +0x4ee
github.com/tendermint/tendermint/blockchain/v1.(*BlockchainReactor).processBlocksRoutine(0xc001c72600, 0xc00a950060)
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/blockchain/v1/reactor.go:298 +0xb6
created by github.com/tendermint/tendermint/blockchain/v1.(*BlockchainReactor).poolRoutine
	/Users/andrew/go/pkg/mod/github.com/pokt-network/tendermint@v0.32.11-0.20200803010950-2b00c2006f24/blockchain/v1/reactor.go:337 +0xf6
```

Was able to restart immediately with no problems

**Comment by andrewnguyen22** [comment]
Was running another tendermint instance in the background, oops.

Closing
