### ISSUE TITLE
Too many files open 

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/pocket-core#788]
```panic: open /Users/Germany/.pocket/data/application.db/000467.log: too many open files
goroutine 150 [running]:
github.com/tendermint/tm-db.(*goLevelDBBatch).Write(0xc00445f740)
	/Users/Germany/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/go_level_db.go:172 +0x7f
github.com/tendermint/tm-db.prefixBatch.Write(...)
	/Users/Germany/go/pkg/mod/github.com/tendermint/tm-db@v0.2.0/prefix_db.go:244
github.com/tendermint/iavl.(*nodeDB).Commit(0xc0000cf090)
	/Users/Germany/go/pkg/mod/github.com/tendermint/iavl@v0.12.4/nodedb.go:332 +0x71
github.com/tendermint/iavl.(*MutableTree).SaveVersion(0xc00001fe90, 0x0, 0x0, 0x0, 0x400000000000e18, 0xffffffffffffffff, 0x0)
	/Users/Germany/go/pkg/mod/github.com/tendermint/iavl@v0.12.4/mutable_tree.go:415 +0xef
github.com/pokt-network/posmint/store/iavl.(*Store).Commit(0xc00001ad00, 0x1bb73ed, 0xa, 0x0, 0x0)
	/Users/Germany/go/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200302134028-19da81a1d77e/store/iavl/store.go:105 +0x37
github.com/pokt-network/posmint/store/rootmulti.commitStores(0xe18, 0xc0005c60f0, 0x18425e6, 0x1e9c920, 0xc004c29ef0, 0xc004c29f20)
	/Users/Germany/go/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200302134028-19da81a1d77e/store/rootmulti/store.go:557 +0x165
github.com/pokt-network/posmint/store/rootmulti.(*Store).Commit(0xc00008e000, 0x0, 0x0, 0x0, 0x0)
	/Users/Germany/go/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200302134028-19da81a1d77e/store/rootmulti/store.go:233 +0x75
github.com/pokt-network/posmint/baseapp.(*BaseApp).Commit(0xc000166b40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/Germany/go/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200302134028-19da81a1d77e/baseapp/baseapp.go:1055 +0x1a8
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc00008b320, 0x0, 0x0, 0x0)
	/Users/Germany/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/abci/client/local_client.go:215 +0xcc
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc000510e30, 0x0, 0x0, 0xd60)
	/Users/Germany/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/proxy/app_conn.go:81 +0x33
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc00013c070, 0xa, 0x0, 0xc001b39600, 0x6, 0xc001b17d00, 0x17, 0xe18, 0x1a9, 0xc007928a40, ...)
	/Users/Germany/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:212 +0x22e
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00013c070, 0xa, 0x0, 0xc001b39600, 0x6, 0xc001b17d00, 0x17, 0xe18, 0x1a9, 0xc007928a40, ...)
	/Users/Germany/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/state/execution.go:166 +0x626
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0000ee000)
	/Users/Germany/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/blockchain/v0/reactor.go:341 +0x967
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/Users/Germany/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/blockchain/v0/reactor.go:118 +0x84```

**Comment by andrewnguyen22** [comment]
closed in favor of #796
