### ISSUE TITLE
Pocket Node throwing an error: "Group's head may grow without bound"

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-core#790]
```
E[2020-04-21|01:55:20.720] Group's head may grow without bound          module=consensus wal=/home/pocket2/.pocket/data/cs.wal/wal head=/home/pocket2/.pocket/data/cs.wal/wal err="open /home/pocket2/.pocket/data/cs.wal/wal: too many open files"
panic: open /home/pocket2/.pocket/data/cs.wal: too many open files

goroutine 287 [running]:
github.com/tendermint/tendermint/libs/autofile.(*Group).readGroupInfo(0xc00048b080, 0x0, 0x0, 0x0, 0x0)
        /home/pocket/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/libs/autofile/group.go:359 +0x547
github.com/tendermint/tendermint/libs/autofile.(*Group).checkTotalSizeLimit(0xc00048b080)
        /home/pocket/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/libs/autofile/group.go:268 +0x64
github.com/tendermint/tendermint/libs/autofile.(*Group).processTicks(0xc00048b080)
        /home/pocket/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/libs/autofile/group.go:239 +0x91
created by github.com/tendermint/tendermint/libs/autofile.(*Group).OnStart
        /home/pocket/go/pkg/mod/github.com/tendermint/tendermint@v0.32.9/libs/autofile/group.go:138 +0x66
```

**Comment by andrewnguyen22** [comment]
closed in favor of #796
