### ISSUE TITLE
pocket gov change_param not working

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-core#963]
**Describe the bug**
Whenever trying the `pocket gov change_param` we get the following error: 

```
panic: Cannot encode unregistered concrete type int.

goroutine 1 [running]:
github.com/tendermint/go-amino.(*Codec).MustMarshalJSON(...)
	/Users/luyzdeleon/go/pkg/mod/github.com/tendermint/go-amino@v0.15.0/amino.go:406
github.com/pokt-network/posmint/x/gov/types.MsgChangeParam.GetSignBytes(0xc000174300, 0x14, 0x30, 0x7ffeefbfecd2, 0x19, 0x4aa2020, 0x4ee5558, 0x0, 0x0, 0x203000)
	/Users/luyzdeleon/go/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200519165031-947a85177d7b/x/gov/types/msg.go:45 +0x152
github.com/pokt-network/posmint/x/auth/types.StdSignBytes(0x7ffeefbfeccb, 0x6, 0xffba569057e4fa3f, 0xc0000f2860, 0x1, 0x1, 0x4f29a00, 0xc000b54180, 0x0, 0x0, ...)
	/Users/luyzdeleon/go/pkg/mod/github.com/pokt-network/posmint@v0.0.0-20200519165031-947a85177d7b/x/auth/types/stdtx.go:107 +0x49
github.com/pokt-network/pocket-core/app/cmd/cli.newTxBz(0xc000139f80, 0x4f29a00, 0xc000b54180, 0xc000174300, 0x14, 0x30, 0x7ffeefbfeccb, 0x6, 0x4f34c80, 0xc00010abc0, ...)
	/Users/luyzdeleon/go/src/github.com/pokt-network/pocket-core/app/cmd/cli/txUtil.go:324 +0x21e
github.com/pokt-network/pocket-core/app/cmd/cli.ChangeParam(0x7ffeefbfeca2, 0x28, 0x7ffeefbfecd2, 0x19, 0x4a97260, 0xc000b521a8, 0xc000b521c0, 0x4, 0x7ffeefbfeccb, 0x6, ...)
	/Users/luyzdeleon/go/src/github.com/pokt-network/pocket-core/app/cmd/cli/txUtil.go:278 +0x34e
github.com/pokt-network/pocket-core/app/cmd/cli.glob..func24(0x5694660, 0xc000019080, 0x4, 0x8)
	/Users/luyzdeleon/go/src/github.com/pokt-network/pocket-core/app/cmd/cli/gov.go:121 +0x28c
github.com/spf13/cobra.(*Command).execute(0x5694660, 0xc000018f00, 0x8, 0x8, 0x5694660, 0xc000018f00)
	/Users/luyzdeleon/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x5698c60, 0x4007b8f, 0xc0000382f8, 0x0)
	/Users/luyzdeleon/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/luyzdeleon/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/pokt-network/pocket-core/app/cmd/cli.Execute()
	/Users/luyzdeleon/go/src/github.com/pokt-network/pocket-core/app/cmd/cli/root.go:43 +0x2d
main.main()
	/Users/luyzdeleon/go/src/github.com/pokt-network/pocket-core/app/cmd/pocket_core/main.go:8 +0x20
```

**To Reproduce**
`pocket gov change_param fa0882e38b2454e20b1ceea15ae386c9cea3aa25 devnet application/MaximumChains "100"`

**Comment by oten91** [comment]
we may have to change MsgChangeParam.ParamVal on POSMint
```
// MsgChangeParam structure for changing governance parameters
type MsgChangeParam struct {
	FromAddress sdk.Address `json:"address"`
	ParamKey    string      `json:"param_key"`
	ParamVal    interface{} `json:"param_value"`
}
```

> A concrete type is some non-interface value (generally a struct) which implements the interface to be (de)serialized. Not all structures need to be registered as concrete types -- only when they will be stored in interface type fields (or interface type slices) do they need to be registered.

https://godoc.org/github.com/tendermint/go-amino

**Comment by oten91** [comment]
@andrewnguyen22  let me know your input
